export const siteConfig = {
  name: "BulkCompress.com",
  description: "Free online bulk file compression tools for images, videos, audio, documents, and archives.",
  url: "https://bulkcompress.com",
  ogImage: "https://bulkcompress.com/og-image.jpg",
  links: {
    twitter: "https://twitter.com/bulkcompress",
    github: "https://github.com/bulkcompress",
    facebook: "https://facebook.com/bulkcompress",
    linkedin: "https://linkedin.com/company/bulkcompress",
  },
  keywords: [
    "file compression",
    "image compression",
    "video compression",
    "audio compression",
    "document compression",
    "archive compression",
    "bulk compression",
    "compress files online",
    "reduce file size",
    "optimize files",
    "free compression tools",
  ],
}
